### ISSUE TITLE
Question about font icon

### ISSUE THREAD

**Issue by Shawnfoto** [bpampuch/pdfmake#2434]
Hello,
May I ask that,
What does mean for "as the text you copy from the fontello-codes.css from the comments (not the escaped value)"

My code is 

```
styles: {
  icon: {
	font: 'Fontello'
  }
}

{ text: '\f096', style: 'icon' }, //icon check-empty

```

**Comment by liborm85** [comment]
fontello-codes.css example:
```css
.icon-emo-happy:before { content: '\e800'; } /* '' */
```

Copy non-escaped value from comment - `/* '' */`, this: ``
